name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        default: "draft"
        options:
          - draft
          - prerelease
          - release

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: windows-latest
            args: '--target x86_64-pc-windows-msvc'
          - platform: ubuntu-20.04
            args: ''
    runs-on: ${{ matrix.config.platform }}
    defaults:
      run:
        working-directory: ./apps/desktop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: DinoZoidDev/subtool

      - name: Install dependencies (ubuntu only)
        if: matrix.config.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Setup rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./apps/desktop/src-tauri -> target"
          cache-on-failure: true

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: false

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install frontend dependencies
        run: pnpm install --filter desktop --ignore-scripts
        
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_AUTH_REDIRECT_PROXY_URL: ${{ secrets.AUTH_REDIRECT_PROXY_URL }}
        
      - name: Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          CARGO_INCREMENTAL: 0
          RUST_BACKTRACE: short
        with:
          tagName: __VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'Subtool v__VERSION__'
          releaseBody: 'See the assets below to download & install this version of Subtool.'
          releaseDraft: ${{ github.event.inputs.release_type == 'draft' }}
          prerelease: ${{ github.event.inputs.release_type == 'prerelease' }}
          args: ${{ matrix.config.args }}
